version: "3.7"
services:
  database:
    image: mysql:8.1
    container_name: java-projet-database
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: toor # Change this password do not use for production
        MYSQL_DATABASE: APTN61_BD
        MYSQL_USER: adm
        MYSQL_PASSWORD: adm
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    container_name: java-projet-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_DATABASE: APTN61_BD
      ADMINER_DEFAULT_USERNAME: adm
